Add initscript

diff --git a/src/main/scripts/service-registry b/src/main/scripts/service-registry
--- a/src/main/scripts/service-registry
+++ b/src/main/scripts/service-registry
@@ -1,116 +1,87 @@
 #!/bin/bash
 #
-# /etc/init.d/service-registry console|start|stop|restart|status
+# /etc/init.d/service-registry start|stop|restart|status|console
 #
-# A Linux start/stop script for Java daemons.
+# A Linux start/stop script for Spring Boot Applications.
 #
-NAME="$(basename $0)"                                                  # the name of the script
-. /etc/sysconfig/${NAME}                                               # Source instance specific config file (JAVA_HOME,JAVA_OPTS, etc.)
-APPLICATION_HOME="/opt/standalone/${NAME}"                             # home of the application executable
-PROG_CONF="/etc/${NAME}/"                                              # home of the configuration files (will be added to classpath)
-JAVA_OPTS_GLOBAL="-Dloader.path=${PROG_CONF},${APPLICATION_HOME}/${NAME}.jar" # global Java Opts
-LOG_DIR="/var/log"                                                     # the path to the logdirectory
-LOG_FILE="$LOG_DIR/$NAME.log"                                          # the absolute path to the logfile
-scriptFile=$(readlink -fn $(type -p $0))                               # the absolute, dereferenced path of this script file
-scriptDir=$(dirname $scriptFile)                                       # absolute path of the script directory
-applDir="$scriptDir"                                                   # home directory of the service application
-serviceName=${NAME}			                                           # service name
+SERVICENAME="$(basename $0)"                                           # The name of the service
+. /etc/sysconfig/${SERVICENAME}                                       # Source instance specific config file (JAVA_HOME,JAVA_OPTS, etc.)
+JAVA_OPTS_GLOBAL="-Dloader.path=${PROG_CONF},${APPLICATION_HOME}/${SERVICENAME}.jar" # Add PROG_CONF to the classpath
 maxShutdownTime=15                                                     # maximum number of seconds to wait for the daemon to terminate normally
-pidFile="/var/run/$serviceName.pid"                              	   # name of PID file (PID = process ID number)
-javaCommand="java"                                                     # name of the Java launcher without the path
-javaExe="$JAVA_HOME/bin/$javaCommand"                                  # file name of the Java application launcher executable
-JAVA_ARGS="-jar ${APPLICATION_HOME}/${NAME}.jar"                       # arguments for Java launcher
-javaCommandLine="$javaExe $JAVA_OPTS $JAVA_OPTS_GLOBAL $JAVA_ARGS $CL_ARGS" # command line to start the Java service application
+JAVA_ARGS="-jar ${APPLICATION_HOME}/${SERVICENAME}.jar"                # arguments for Java launcher
+javaCommandLine="$JAVA_HOME/bin/java $JAVA_OPTS $JAVA_OPTS_GLOBAL $JAVA_ARGS $PROG_ARGS" # command line to start the Java service application
 
 #make the log directory if it doesn't exist
 if [ ! -d "$LOG_DIR" ] ; then
    mkdir $LOG_DIR
 fi
 
-# Makes the file $1 writable by the group $GROUP.
-function makeFileWritable {
-   local filename="$1"
-   touch $filename || return 1
-   chgrp $GROUP $filename || return 1
-   chown $USER $filename || return 1
-   chmod g+w $filename || return 1
-   return 0; }
-
-# Returns 0 if the process with PID $1 is running.
-function checkProcessIsRunning {
-   local pid="$1"
-   if [ -z "$pid" -o "$pid" == " " ]; then return 1; fi
-   if [ ! -e /proc/$pid ]; then return 1; fi
-   return 0; }
-
-# Returns 0 if the process with PID $1 is our Java service process.
-function checkProcessIsOurService {
-   local pid="$1"
-   local cmd="$(ps -p $pid --no-headers -o comm)"
-   if [ "$cmd" != "$javaCommand" -a "$cmd" != "$javaCommand.bin" ]; then return 1; fi
-   grep -q --binary -F "$serviceName" /proc/$pid/cmdline
-   if [ $? -ne 0 ]; then return 1; fi
-   return 0; }
-
 # Returns 0 when the service is running and sets the variable $servicePid to the PID.
 function getServicePid {
    if [ ! -f $pidFile ]; then return 1; fi
    servicePid="$(<$pidFile)"
-   checkProcessIsRunning $servicePid || return 1
-   checkProcessIsOurService $servicePid || return 1
    return 0; }
 
+function isProcessRunning {
+  if getServicePid
+  then
+    if ps -p $servicePid > /dev/null
+	then
+		echo "Service is running"
+		return 0 
+	fi
+  fi
+  return 1
+}
+
 function startServiceProcess {
-   cd $applDir || return 1
    rm -f $pidFile
-   makeFileWritable $pidFile || return 1
-   makeFileWritable $LOG_FILE || return 1
-   local cmd="setsid $javaCommandLine >>$LOG_FILE 2>&1 & echo \$! >$pidFile"
-   sudo -u $USER $SHELL -c "$cmd" || return 1
-   sleep 0.1
+   nohup $javaCommandLine >/dev/null 2>&1 &
+   sleep 5
    servicePid="$(<$pidFile)"
-   if checkProcessIsRunning $servicePid; then :; else
-      echo -ne "\n$serviceName start failed, see logfile."
+   if isProcessRunning; then :; else
+      echo -ne "\n$SERVICENAME start failed, see logfile."
       return 1
       fi
-   return 0; }
+   return 0; 
+}
 
 function stopServiceProcess {
    kill $servicePid || return 1
    for ((i=0; i<maxShutdownTime*10; i++)); do
-      checkProcessIsRunning $servicePid
+      isProcessRunning
       if [ $? -ne 0 ]; then
-         rm -f $pidFile
+         #rm -f $pidFile
          return 0
-         fi
+      fi
       sleep 0.1
-      done
-   echo -e "\n$serviceName did not terminate within $maxShutdownTime seconds, sending SIGKILL..."
+   done
+   echo -e "\n$SERVICENAME did not terminate within $maxShutdownTime seconds, sending SIGKILL..."
    kill -s KILL $servicePid || return 1
    local killWaitTime=15
    for ((i=0; i<killWaitTime*10; i++)); do
-      checkProcessIsRunning $servicePid
+      isProcessRunning
       if [ $? -ne 0 ]; then
          rm -f $pidFile
          return 0
-         fi
+      fi
       sleep 0.1
-      done
-   echo "Error: $serviceName could not be stopped within $maxShutdownTime+$killWaitTime seconds!"
-   return 1; }
+   done
+   echo "Error: $SERVICENAME could not be stopped within $maxShutdownTime+$killWaitTime seconds!"
+   return 1; 
+}
 
 function runInConsoleMode {
    getServicePid
-   if [ $? -eq 0 ]; then echo "$serviceName is already running"; return 1; fi
-   cd $applDir || return 1
-   sudo -u $USER $javaCommandLine || return 1
+   if [ $? -eq 0 ]; then echo "$SERVICENAME is already running"; return 1; fi
+   $javaCommandLine || return 1
    if [ $? -eq 0 ]; then return 1; fi
    return 0; }
 
 function startService {
    getServicePid
-   if [ $? -eq 0 ]; then echo -n "$serviceName is already running"; RETVAL=0; return 0; fi
-   echo -n "Starting $serviceName   "
+   if [ $? -eq 0 ]; then echo -n "$SERVICENAME is already running"; RETVAL=0; return 0; fi
+   echo -n "Starting $SERVICENAME   "
    startServiceProcess
    if [ $? -ne 0 ]; then RETVAL=1; echo "failed"; return 1; fi
    echo "started PID=$servicePid"
@@ -118,17 +89,17 @@ function startService {
    return 0; }
 
 function stopService {
-   getServicePid
-   if [ $? -ne 0 ]; then echo -n "$serviceName is not running"; RETVAL=0; echo ""; return 0; fi
-   echo -n "Stopping $serviceName   "
+   isProcessRunning
+   if [ $? -ne 0 ]; then echo -n "$SERVICENAME is not running"; RETVAL=0; echo ""; return 0; fi
+   echo -n "Stopping $SERVICENAME   "
    stopServiceProcess
    if [ $? -ne 0 ]; then RETVAL=1; echo "failed"; return 1; fi
    echo "stopped PID=$servicePid"
    return 0; }
 
 function checkServiceStatus {
-   echo -n "Checking for $serviceName:   "
-   if getServicePid; then
+   echo -n "Checking for $SERVICENAME:   "
+   if isProcessRunning; then
       echo "running PID=$servicePid"
       RETVAL=0
    else
@@ -156,7 +127,7 @@ function main {
          checkServiceStatus
          ;;
       *)
-         echo "Usage: $0 {console|start|stop|restart|status}"
+         echo "Usage: $0 {start|stop|restart|status|console|debug}"
          exit 1
          ;;
       esac
